/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUIpack;
import java.sql.*;
/**
 *
 * @author sreekanth
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    NewFrame nf;
    Display dsp;
    Statement stm;
    Statement stm2;
    public Dashboard(NewFrame nf,Display dsp,Statement stm,Statement stm2) {
        initComponents();
        this.nf = nf;
        this.dsp = dsp;
        this.stm=stm;
        this.stm2 = stm2;
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dashboardBtn = new javax.swing.JButton();
        findcarBtn = new javax.swing.JButton();
        rentcarBtn = new javax.swing.JButton();
        profileBtn = new javax.swing.JButton();
        bookingbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernamebox = new javax.swing.JLabel();
        emailbox = new javax.swing.JLabel();
        mobilebox = new javax.swing.JLabel();
        locationbox = new javax.swing.JLabel();
        licensebox = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(844, 686));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(163, 686));

        dashboardBtn.setText("Dashboard");
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });

        findcarBtn.setText("Find cars");
        findcarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findcarBtnActionPerformed(evt);
            }
        });

        rentcarBtn.setText("Rent cars");
        rentcarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentcarBtnActionPerformed(evt);
            }
        });

        profileBtn.setText("Profile");
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });

        bookingbtn.setText("My Bookings");
        bookingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(profileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashboardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(findcarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rentcarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookingbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(dashboardBtn)
                .addGap(47, 47, 47)
                .addComponent(profileBtn)
                .addGap(38, 38, 38)
                .addComponent(findcarBtn)
                .addGap(48, 48, 48)
                .addComponent(rentcarBtn)
                .addGap(45, 45, 45)
                .addComponent(bookingbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Dashboard");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIpack/images/user-icon100.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        usernamebox.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        usernamebox.setText("Username");

        emailbox.setText("emailaddress@gmail.com");

        mobilebox.setText("9847123456");

        locationbox.setText("Location");

        licensebox.setText("License no");

        updateBtn.setBackground(new java.awt.Color(0, 102, 255));
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update profile");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("My Cars");

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIpack/images/mobilepic (2).jpg"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(24, 25));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIpack/images/mailpic (2).jpg"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(24, 25));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIpack/images/locationpic (2).jpg"))); // NOI18N
        jLabel5.setText("jLabel3");
        jLabel5.setPreferredSize(new java.awt.Dimension(24, 25));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIpack/images/id-card (2).png"))); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(24, 25));

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateBtn)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(locationbox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(licensebox)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(usernamebox)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailbox)
                                            .addComponent(mobilebox)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(219, 219, 219)
                                        .addComponent(homeBtn)
                                        .addGap(26, 26, 26)
                                        .addComponent(logoutBtn))))
                            .addComponent(jLabel8))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mobilebox)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(locationbox)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailbox))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel1)
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(logoutBtn)
                                            .addComponent(homeBtn))
                                        .addGap(117, 117, 117)
                                        .addComponent(licensebox)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateBtn)
                                    .addComponent(usernamebox))))
                        .addGap(53, 64, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void init(){
        jPanel4.removeAll();
        String username="",email="",phone="",location="",license="";
        
        int currentuser=nf.userid;
        
        String query="select username,email,phone,location,license from User where userid=" +currentuser+ "";
        try{
            ResultSet rs = stm.executeQuery(query);
            while(rs.next()){
                username=rs.getString("username");
                email=rs.getString("email");
                phone=rs.getString("phone");
                location=rs.getString("location");
                license=rs.getString("license");
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
        
        usernamebox.setText(username);
        emailbox.setText(email);
        mobilebox.setText(phone);
        locationbox.setText(location);
        licensebox.setText(license);
        
        String cname="",ctype="",ftype="",status="",rent="";
        
        int cid=0;
        String query2 = "select name,cartype,fueltype,carid,isbooked,rent from Car where ownerid = "+currentuser;
        try {
            ResultSet rs2 = stm.executeQuery(query2);
            while(rs2.next())
            {
                String uname="Not booked",uphone="",uemail="";
                cid = rs2.getInt("carid");
                cname = rs2.getString("name");
                ctype = rs2.getString("cartype");
                ftype = rs2.getString("fueltype");
                status = rs2.getString("isbooked");
                rent = rs2.getString("rent");
                if(status.equals("True"))
                {
                    //String query3 = "select U.fname,U.phone,U.email from User U,Booking B where  B.userid=U.userid";
                    String query3 = "select fname,phone,email from User where userid in (select userid from Booking where carid = "+cid+")";
                    ResultSet rs3 = stm2.executeQuery(query3);
                    while(rs3.next())
                    {
                        uname = rs3.getString("fname");
                        uphone = rs3.getString("phone");
                        uemail = rs3.getString("email");
                    }
                }
    
                Carbook2 cb=new Carbook2(cname,ctype,ftype,location,rent,uname,uphone,uemail);
                jPanel4.add(cb);
                System.out.println("added");
            }
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        jPanel4.revalidate();
        jPanel4.repaint();
        nf.repaint();
    }
    
    
    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        // TODO add your handling code here:
        nf.state = 4;
        dsp.render();
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        // TODO add your handling code here:
        nf.state = 7;
        dsp.render();
    }//GEN-LAST:event_profileBtnActionPerformed

    private void findcarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findcarBtnActionPerformed
        // TODO add your handling code here:
        nf.state = 5;
        dsp.render();
    }//GEN-LAST:event_findcarBtnActionPerformed

    private void rentcarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentcarBtnActionPerformed
        // TODO add your handling code here:
        nf.state = 6;
        dsp.render();
    }//GEN-LAST:event_rentcarBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        nf.setLogedin(false);
        nf.state = 0;
        dsp.render();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        nf.state = 3;
        dsp.render();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        nf.state = 7;
        dsp.render();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void bookingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingbtnActionPerformed
        // TODO add your handling code here:
        nf.state = 8;
        dsp.render();
    }//GEN-LAST:event_bookingbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookingbtn;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JLabel emailbox;
    private javax.swing.JButton findcarBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel licensebox;
    private javax.swing.JLabel locationbox;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel mobilebox;
    private javax.swing.JButton profileBtn;
    private javax.swing.JButton rentcarBtn;
    private javax.swing.JButton updateBtn;
    private javax.swing.JLabel usernamebox;
    // End of variables declaration//GEN-END:variables
}
